export default {
  Login: {
    kLogin: 'Login',
    kWelcomeBack: 'Welcome Back!',
    kEmailAddress: 'Email address',
    kPassword: 'Password',
    kForgot: 'Forgot Password?',
    kSignIn: 'Sign In',
    kGoogle: 'Continue with Google',
    kYoutube: 'Continue with You Tube',
    kFacebook: 'Continue with Businees Instagram',
    kInstagram: 'Continue with Instagram',
    kTikTok: 'Continue with TikTok',
    kSend: 'Send',
  },
  SignUp: {
    kFullName: 'Full Name',
    kConfirmPassword: 'Confirm Password',
    kSignUp: 'Sign Up',
    kAlready: 'Already have an account? ',
    kRegister: 'By registering you agree to ',
    kTerms: 'Terms & Conditions',
    kAnd: ' and ',
    kPrivacy: 'Privacy Policy',
    kBitcomer: ' of the Bitcomer ',
  },
  ChoosePhoto: {
    kChoosePhoto: 'Choose Photo',
    kTakeSelfie: 'Or take a selfie',
    kStandardCombo: 'Standard Combo',
    kIncludeoriginal: 'Include original',
    kRateresults: 'Rate this results',
    kSignupToGet: 'Sign Up To Get  1 Image Credit',
    kNowaterMarkimage: '(No waterMark, High-res image)',
    kGoPremium: 'Go Premium',
  },
  Premium: {
    kNoWatermark: 'No waterMark',
    kHighresolution: 'High resolution images',
    kFasterSpeed: 'Faster Speed',
    kContinue: 'Continue',
  },
  Settings: {
    kSetting: 'Setting',
    kEdit: 'Edit Profile',
    kChangePassword: 'Change Password',
    kRateus: 'Rate us on the App Store',
    kShareApp: 'Share App',
    kHelp: 'Help',
    kTerms: 'Terms and conditions',
    kPrivacy: 'Privacy policy',
    kLogout: 'Logout',
    kEditProfile: 'Edit Profile',
    kUpdateProfile: 'Update your Profile',
  },
};
